#!/usr/bin/env python3
"""
Prepare mandatory morning context before Lisa's editorial cycle.

This script is intentionally deterministic: it only reads local state and writes
one dated context file that the heartbeat instructions can require Lisa to load.
"""
import datetime
import os
from pathlib import Path


WORKSPACE = Path(os.path.expanduser("~/.openclaw/workspace"))
CACHE = WORKSPACE / "cache"
TODAY = datetime.date.today()
YESTERDAY = TODAY - datetime.timedelta(days=1)


def read_if_exists(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def main() -> int:
    CACHE.mkdir(parents=True, exist_ok=True)

    today_learning = CACHE / f"session_learnings_{TODAY:%Y-%m-%d}.md"
    yesterday_learning = CACHE / f"session_learnings_{YESTERDAY:%Y-%m-%d}.md"
    rejected_topics = CACHE / "rejected_topics.jsonl"
    output = CACHE / f"morning_context_{TODAY:%Y-%m-%d}.md"
    latest = CACHE / "morning_context_latest.md"

    yesterday_text = read_if_exists(yesterday_learning)
    today_text = read_if_exists(today_learning)
    rejected_text = read_if_exists(rejected_topics)

    content = f"""# Morning Context — {TODAY:%Y-%m-%d}

Generated by: `scripts/morning_context.py`

## Mandatory Use

Lisa MUST load and apply this context before DATA GATE, signal scoring, Roman Test,
portfolio selection and report writing.

## Yesterday Learning

Source: `{yesterday_learning}`

{yesterday_text if yesterday_text else "(no yesterday learning file found)"}

## Today Learning / Current Corrections

Source: `{today_learning}`

{today_text if today_text else "(no today learning file found)"}

## Recent Rejected Topics

Source: `{rejected_topics}`

{rejected_text[-4000:] if rejected_text else "(no rejected topics file found)"}

## Hard Editorial Rules For This Run

- Do not repeat a rejected topic unless there is a new concrete news peg.
- Do not promote SEO gaps into CREATE unless Roman Test passes.
- Run duplicate/cannibalization checks before CREATE.
- If Google Trends primary provider fails, use pytrends; never invent Trends data.
- API and credential checks must run in the main session, never in subagents.
"""

    output.write_text(content, encoding="utf-8")
    latest.write_text(content, encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
